Section "InputClass"
        Identifier "evdev touchpad catchall"
        Driver "evdev"
        MatchIsTouchpad "on"
        Option "SendCoreEvents" "true"
        Option "MinSpeed" "0.5"
        Option "MaxSpeed" "1.0"
        Option "AccelFactor" "0.05"
        Option "ConstantDeceleration" "2.0"
EndSection

Section "InputClass"
        Identifier "evdev keyboard catchall"
        Driver "evdev"
        MatchIsKeyboard "on"
        Option "SendCoreEvents" "true"
EndSection

Section "InputClass"
        Identifier "evdev pointer catchall"
        Driver "evdev"
        MatchIsPointer "on"
        Option "SendCoreEvents" "true"
        Option "Emulate3Buttons" "false"
        Option "Emulate3Timeout" "50"
EndSection
