#!/bin/sh
GAME_DEV="/dev/disk/by-partlabel/GAME"
SCORE_DEV="/dev/disk/by-partlabel/SCORE"

# Mount Score Partition for highscores
[ -b "$SCORE_DEV" ] && mount -o rw,noatime "$SCORE_DEV" /var/data

# Unlock Game Partition via TPM
if cryptsetup isLuks "$GAME_DEV"; then
    tpm2_unseal -c 0x81010002 | cryptsetup luksOpen "$GAME_DEV" game_crypt -d -
    mount -o ro,nosuid,nodev /dev/mapper/game_crypt /opt/game
fi