#!/bin/sh

if [ ! -b /dev/disk/by-partlabel/GAME ]; then
    # Start the warning dialogue inside a self-terminating X session in the background
    startx /usr/bin/start_warn.sh -- -nocursor -quiet &
fi