#!/bin/sh

# Only start if the game drive is actually there and mounted
if [ -d "/opt/game" ]; then
    echo "Launching game bootstrap..."
    
    (
        while true; do
            /usr/bin/xinit /usr/bin/start_game.sh -- /usr/bin/Xorg :0 vt7 -nocursor -quiet -s 0 -dpms
            sleep 1
        done
    ) &
fi