name: Build SWACS-1D OS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev rsync cpio python3 unzip bc wget zstd libssl-dev file

      - name: Restore Download Cache
        uses: actions/cache/restore@v4
        with:
          path: ~/buildroot_dl
          key: br-dl-${{ hashFiles('os/configs/swacs1d_defconfig') }}
          restore-keys: br-dl-

      - name: Clone Buildroot
        run: |
          git clone --depth 1 --branch 2024.02.x https://git.buildroot.net/buildroot

      - name: Prep Board Files (Fixes Rsync Error)
        run: |
          # Copy your custom board and config files INTO the buildroot directory
          cp -r os/board/swacs1d buildroot/board/
          cp os/configs/swacs1d_defconfig buildroot/configs/

      - name: Build OS
        run: |
          cd buildroot
          make swacs1d_defconfig
          # Point Buildroot to the cache folder
          echo "BR2_DL_DIR=\"/home/runner/work/buildroot_dl\"" >> .config
          make -j$(nproc)

      - name: Save Download Cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: ~/buildroot_dl
          key: br-dl-${{ hashFiles('os/configs/swacs1d_defconfig') }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SWACS-1D-OS-Image
          path: buildroot/output/images/swacs1d.img